#!/usr/bin/env python3
# SPDX-FileCopyrightText: Johannes Wilm
# SPDX-License-Identifier: GPL-3.0-or-later
"""Whale Instructor Python-to-C / Python-to-JS transpiler (clean-room).

Translates a small, explicitly-imported Python dialect into the user_main.c
consumed by build_tc.py, or — with --target js — into the
async JavaScript executed live over Bluetooth by the `whale` runtime
(static/js/whale_ble.js):

    from whale import A, set_motor, sleep

    def main():
        set_motor(A, 50)
        sleep(3000)
        set_motor(A, 0)

Entry points: def main() -> user_main(); def task(), def task1() ... task15()
or def user_taskN() -> user_taskN() (the build adds -DUSER_TASKN for each).
Other top-level def's become static C helpers. Supported: int/float
arithmetic, if/elif/else, while, for i in range(a, b) / range(a, b, literal
step), break/continue/return/pass, calls, and/or/not, comparisons. Star
imports are rejected on purpose: import exactly what you use. Unknown or
unimported names are hard errors with the offending line number. No print
(use display_digital_tube), no strings/lists/dicts (the device API is
numeric).

Special form: display_custom(port, r0, r1, ..., r7) takes eight row
bitmasks (0..255, top row first) and emits an 8x8 LED matrix pattern.

Usage: python3 py2c.py program.py [-o user_main.c] [--target c|js]
"""
import ast
import json
import re
import sys

GPL_HEADER = """\
/* Generated by Whale Instructor (py2c.py) from the user's program.
 * The generated code belongs to the program's author, who may license
 * their own program however they like -- the Whale Instructor GPL does
 * not apply to user programs (see LICENSE_EXCEPTION.md).
 */
#include "whale_instructor.h"
"""

JS_HEADER = """\
// Generated by Whale Instructor (py2c.py) from the user's program.
// The generated code belongs to the program's author, who may license
// their own program however they like -- the Whale Instructor GPL does
// not apply to user programs (see LICENSE_EXCEPTION.md).
// Runs live over Bluetooth against the `whale` runtime (js/whale_ble.js).
"""

# Modules the dialect import accepts. 'whale' is the documented short form;
# 'whale_instructor' is the full package name.
DIALECT_MODULES = ('whale', 'whale_instructor')
DIALECT_DOC = 'whale'

# --- API tables (facts taken from the vendor whalesbot.h we compile
# --- against; the generated C keeps the vendor's C ABI names) --------------

API_CONSTS = (
    ['MotorAll', 'A', 'B', 'C', 'D']
    + ['P%d' % i for i in range(1, 6)]   # Port_ID: P1..P5 (SCRATCH_STD build)
    + ['move_forward', 'move_backward', 'move_turnleft', 'move_turnright']
    + ['black_line', 'white_line']
    + ['switch_off', 'switch_on']
    + ['key_enter', 'key_left', 'key_right']
    + ['turn_left', 'turn_center', 'turn_right']            # Turn_Type
    + ['intersection_left', 'intersection_T', 'intersection_right']
    + ['compare_less_than', 'compare_greater_than', 'compare_equal',
       'compare_not_equal']                                  # Compare_Opt
    + ['omni_turnleft', 'omni_turnright']                    # Omni_Turn_Type
    + ['color_white', 'color_yellow', 'color_purple', 'color_cyan',
       'color_red', 'color_green', 'color_blue', 'color_black']
    + ['S%d' % i for i in range(1, 19)]                      # Servo_ID
    + ['AI_image_%d' % i for i in range(10)]                 # AI_Image_ID
    + ('sound_airplane sound_automobile sound_bird sound_brake sound_bye '
       'sound_bye_en sound_cannon sound_cat sound_cattle sound_cock '
       'sound_concerned sound_concerned_en sound_dinosaur sound_dog sound_duck '
       'sound_heartbeat sound_helicopter sound_hi sound_hi_en sound_horn '
       'sound_horse sound_laugh sound_piano_do sound_piano_DO sound_piano_fa '
       'sound_piano_la sound_piano_mi sound_piano_re sound_piano_si '
       'sound_piano_so sound_press_key sound_sheep sound_tank sound_thanks '
       'sound_thanks_en sound_welcome sound_welcome_en sound_whistling '
       'sound_wow').split()
    + ('LED_symbol_0 LED_symbol_1 LED_symbol_2 LED_symbol_3 LED_symbol_4 '
       'LED_symbol_5 LED_symbol_6 LED_symbol_7 LED_symbol_8 LED_symbol_9 '
       'LED_symbol_A LED_symbol_B LED_symbol_C LED_symbol_D LED_symbol_E '
       'LED_symbol_F LED_symbol_G LED_symbol_H LED_symbol_I LED_symbol_J '
       'LED_symbol_K LED_symbol_L LED_symbol_M LED_symbol_N LED_symbol_O '
       'LED_symbol_P LED_symbol_Q LED_symbol_R LED_symbol_S LED_symbol_T '
       'LED_symbol_U LED_symbol_V LED_symbol_W LED_symbol_X LED_symbol_Y '
       'LED_symbol_Z LED_symbol_forward LED_symbol_backward LED_symbol_left '
       'LED_symbol_turnleft LED_symbol_turnright LED_symbol_stop LED_symbol_GO '
       'LED_symbol_big_heart LED_symbol_little_heart LED_symbol_plus '
       'LED_symbol_minus LED_symbol_multiplied LED_symbol_divided '
       'LED_symbol_equal LED_symbol_exclamation LED_symbol_question_mark '
       'LED_symbol_dollar LED_symbol_RMB').split()
    + ('LED_emoji_eye LED_emoji_smile LED_emoji_sad LED_emoji_naughty '
       'LED_emoji_surprised LED_emoji_flare LED_emoji_tears LED_emoji_avarice '
       'LED_emoji_beckoning LED_emoji_anger LED_emoji_dizzy LED_emoji_grim'
      ).split()
)

# name -> (param kinds, ret kind); kind: 'i' int, 'f' float
def F(*kinds, r='i'):
    return (list(kinds), r)

API_FUNCS = {
    'set_motor': F('i', 'i'),
    'set_motor_time': F('i', 'i', 'f'),
    'set_dual_motor_time': F('i', 'i', 'i', 'i', 'f'),
    'set_motor_angle': F('i', 'i', 'i'),
    'set_dual_motor_angle': F('i', 'i', 'i', 'i', 'i'),
    'off_motor': F('i'),
    'reverse_motor': F('i'),          # vendor core; declaration in our header
    'get_motor_speed': F('i'),
    'move': F('i', 'i'),
    'move_time': F('i', 'i', 'f'),
    'stop_move': F(),
    'omni_wheel_ctrl': F('f', 'f'),   # float speed %, heading in degrees
    'omni_wheel_turn': F('i', 'i'),
    'omni_wheel_stop': F(),
    'play_sound': F('i'),
    'set_light': F('i', 'i'),
    'set_magnet': F('i', 'i'),
    'display_emotion': F('i', 'i', 'i'),
    'off_emotion': F('i', 'i'),
    'display_symbol': F('i', 'i'),
    # special form: display_custom(port, r0..r7) -> 8x8 matrix rows
    'display_custom': F('i', 'i', 'i', 'i', 'i', 'i', 'i', 'i', 'i'),
    'off_LED': F('i'),
    'display_digital_tube': F('i', 'i'),
    'display_digital_tube_score': F('i', 'i', 'i'),
    'off_digital_tube': F('i'),
    'display_screen': F('i'),
    'clear_screen': F(),
    'read_number': F('i'),
    'set_display_num': F('i'),
    'set_RGB': F('i', 'i', 'i', 'i'),
    'set_RGB_color': F('i', 'i'),
    'off_RGB_color': F('i'),
    'set_servo_angle': F('i', 'i', 'i'),
    'set_servo_rotation': F('i', 'i'),
    'restore_torque': F(),
    'get_integrated_grayscale': F('i'),
    'integrated_grayscale_detected': F('i', 'i'),
    'get_infrared_distance': F('i'),
    'obstacle_infrared_detected': F('i'),
    'touch_switch_pressed': F('i'),
    'get_ambient_light': F('i'),
    'get_single_grayscale': F('i'),
    'single_grayscale_detected': F('i', 'i'),
    'get_temperature': F('i', r='f'),  # vendor control.h: float(u8)
    'get_humidity': F('i', r='f'),     # vendor control.h: float(u8)
    'get_flame': F('i'),
    'magnetic_detected': F('i'),
    'get_ultrasonic_distance': F('i'),
    'get_sound_volume': F('i'),
    'get_encoder_value': F('i'),      # motor encoder, port A..D
    'reset_motor_encoder': F('i'),
    'get_bt_remote_control': F(r='i'),  # raw Bluetooth remote bitmask
    'button_pressed': F('i'),
    'get_digital_input': F('i'),
    'get_analog_input': F('i'),
    'read_EEPROM': F('i'),
    'write_EEPROM': F('i', 'i'),
    'set_digital_output': F('i', 'i'),
    'color_value': F('i'),
    'color_detected': F('i', 'i'),
    'get_AI_image': F('i'),           # AI camera module only (not MC101s)
    'get_AI_voice': F(r='i'),         # AI voice module only (not MC101s)
    'random_number': F('i', 'i'),
    'math_modulus': F('i', 'i'),
    'timer': F(r='f'),
    'reset_timer': F(),
    'recorder': F('i'),
    'play_record': F(),
    'patrol_integrated_initialization': F('i', 'i', 'i', 'i'),
    'patrol_single_initialization': F('i', 'i', 'i', 'i', 'i', 'i', 'i', 'i',
                                      'i'),
    'patrol_omni_wheel_integrated_init': F('i', 'i', 'i', 'i'),
    'patrol_omni_wheel_single_init': F('i', 'i', 'i', 'i', 'i', 'i', 'i', 'i',
                                       'i'),
    'patrol_ambient_detection': F(),
    'patrol_speed': F('i'),
    'patrol_road': F('i', 'i', 'f'),
    'patrol_time': F('i', 'f'),
    'patrol_turn': F('i', 'i', 'i'),
    'start_motor_time': F('i', 'i', 'f'),
    'start_motor_angle': F('i', 'i', 'i'),
    'start_motor_sensor': F('i', 'i', 'i', 'i', 'i'),
    'patrol_button': F(),
    'vTaskDelay': F('i'),
    'sleep': F('i'),   # sugar; emitted as vTaskDelay
    'wait': F('i'),    # alias for sleep; emitted as vTaskDelay
}

BINOPS = {ast.Add: '+', ast.Sub: '-', ast.Mult: '*', ast.FloorDiv: '/',
          ast.Mod: '%', ast.Div: '/'}
CMPOPS = {ast.Eq: '==', ast.NotEq: '!=', ast.Lt: '<', ast.LtE: '<=',
          ast.Gt: '>', ast.GtE: '>='}

# ---- API reference (served by the IDE help panel; keep in sync) ------------
# name -> (category, signature, description)

API_HELP = {
    # motors
    'set_motor': ('Motors', 'set_motor(motor, speed)',
                  'Run one motor (A, B, C, D) at speed -100..100. 0 = stop.'),
    'set_motor_time': ('Motors', 'set_motor_time(motor, speed, seconds)',
                       'Run one motor for a time, then it stops.'),
    'set_dual_motor_time': ('Motors',
                            'set_dual_motor_time(m1, s1, m2, s2, seconds)',
                            'Run two motors at different speeds for a time.'),
    'set_motor_angle': ('Motors', 'set_motor_angle(motor, speed, degrees)',
                        'Rotate one motor by an angle (encoder-based).'),
    'set_dual_motor_angle': ('Motors',
                             'set_dual_motor_angle(m1, s1, m2, s2, degrees)',
                             'Rotate two motors by an angle.'),
    'off_motor': ('Motors', 'off_motor(motor)', 'Switch one motor off.'),
    'reverse_motor': ('Motors', 'reverse_motor(motor)',
                      'Reverse the spin direction of a motor.'),
    'get_motor_speed': ('Motors', 'get_motor_speed(motor)',
                        'Read back the current speed of a motor.'),
    'get_encoder_value': ('Sensors', 'get_encoder_value(motor)',
                          'Read the motor encoder counter (A..D).'),
    'reset_motor_encoder': ('Sensors', 'reset_motor_encoder(motor)',
                            'Reset a motor encoder counter to 0.'),
    # driving
    'move': ('Driving', 'move(direction, speed)',
             'Drive both wheels: move_forward, move_backward, '
             'move_turnleft, move_turnright.'),
    'move_time': ('Driving', 'move_time(direction, speed, seconds)',
                  'Drive for a time, then stop.'),
    'stop_move': ('Driving', 'stop_move()', 'Stop driving immediately.'),
    'omni_wheel_ctrl': ('Driving', 'omni_wheel_ctrl(power, degrees)',
                        'Omni-wheel move at power % towards a heading in '
                        'degrees (needs the 4-motor omni base).'),
    'omni_wheel_turn': ('Driving', 'omni_wheel_turn(direction, power)',
                        'Omni-wheel spin: omni_turnleft / omni_turnright.'),
    'omni_wheel_stop': ('Driving', 'omni_wheel_stop()', 'Stop omni-wheel move.'),
    # display
    'display_digital_tube': ('Display', 'display_digital_tube(port, number)',
                             'Show a number on a digital tube display.'),
    'display_digital_tube_score': ('Display',
                                   'display_digital_tube_score(p, left, right)',
                                   'Show two numbers (a score) on a tube.'),
    'off_digital_tube': ('Display', 'off_digital_tube(port)',
                         'Clear a digital tube display.'),
    'display_screen': ('Display', 'display_screen(number)',
                       'Show a number on the controller screen.'),
    'clear_screen': ('Display', 'clear_screen()', 'Clear the controller '
                     'screen.'),
    'display_symbol': ('Display', 'display_symbol(port, symbol)',
                       'Show a LED_symbol_* pattern on a matrix display.'),
    'display_emotion': ('Display', 'display_emotion(left_port, right_port, '
                        'emoji)',
                        'Show a LED_emoji_* face across two matrix eyes.'),
    'off_emotion': ('Display', 'off_emotion(left_port, right_port)',
                    'Clear the emotion eyes.'),
    'display_custom': ('Display', 'display_custom(port, r0, r1, ..., r7)',
                       'Draw an 8x8 pattern: eight row bitmasks 0..255, '
                       'top row first. 0b11111111 = 255 = full row.'),
    'read_number': ('Display', 'read_number(number)',
                    'Play a number through the audio pipeline '
                    '(vendor PlaySensorNum; needs the speech data and '
                    'speaker). Does not draw on the screen.'),
    'set_display_num': ('Display', 'set_display_num(number)',
                        'Show a number (0..9999) on the controller '
                        'face display.'),
    'set_RGB': ('Display', 'set_RGB(port, r, g, b)',
                'Set an RGB LED light by red/green/blue 0..255.'),
    'set_RGB_color': ('Display', 'set_RGB_color(port, color)',
                      'Set an RGB LED from a named color (color_red, ...).'),
    'off_RGB_color': ('Display', 'off_RGB_color(port)', 'Turn an RGB light '
                      'off.'),
    'off_LED': ('Display', 'off_LED(port)', 'Turn an LED port off.'),
    'set_light': ('Display', 'set_light(port, state)',
                  'Switch a light on/off (switch_on / switch_off).'),
    # sound
    'play_sound': ('Sound', 'play_sound(sound)',
                   'Play a built-in sound (sound_dog, sound_laugh, '
                   'sound_piano_do, ...).'),
    'recorder': ('Sound', 'recorder(port)',
                 'Record sound to the module on a port.'),
    'play_record': ('Sound', 'play_record()', 'Play back the recording.'),
    'set_magnet': ('Sound', 'set_magnet(port, state)',
                   'Electromagnet on/off (switch_on / switch_off).'),
    # sensors
    'touch_switch_pressed': ('Sensors', 'touch_switch_pressed(port)',
                             'True while the touch switch is pressed.'),
    'obstacle_infrared_detected': ('Sensors',
                                   'obstacle_infrared_detected(port)',
                                   'True while the IR sensor sees an '
                                   'obstacle.'),
    'get_infrared_distance': ('Sensors', 'get_infrared_distance(port)',
                              'IR ranging value (0..~4000, smaller = '
                              'closer).'),
    'get_ultrasonic_distance': ('Sensors', 'get_ultrasonic_distance(port)',
                                'Ultrasonic distance in cm.'),
    'get_integrated_grayscale': ('Sensors',
                                 'get_integrated_grayscale(channel)',
                                 '5-in-1 grayscale channel 1..5 reading '
                                 '(0..100, higher = darker: black line is '
                                 'above ~60, white below ~20). Must call '
                                 'patrol_integrated_initialization first or '
                                 'the controller crashes!'),
    'integrated_grayscale_detected': ('Sensors',
                                      'integrated_grayscale_detected(ch, '
                                      'line)',
                                      'True if black_line (reading > ~60) '
                                      'or white_line (< ~20) under the '
                                      '5-in-1 sensor channel 1..5.'),
    'get_single_grayscale': ('Sensors', 'get_single_grayscale(port)',
                             'Single grayscale value (0..100, higher = '
                             'darker: black line above ~50, white below '
                             '~20).'),
    'single_grayscale_detected': ('Sensors', 'single_grayscale_detected(p, '
                                  'line)',
                                  'True if black_line (reading > ~50) or '
                                  'white_line (< ~20) detected.'),
    'get_ambient_light': ('Sensors', 'get_ambient_light(port)',
                          'Ambient light sensor value.'),
    'get_temperature': ('Sensors', 'get_temperature(port)',
                        'Temperature sensor reading in Celsius.'),
    'get_humidity': ('Sensors', 'get_humidity(port)',
                     'Humidity sensor reading in percent.'),
    'get_flame': ('Sensors', 'get_flame(port)', 'Flame sensor value.'),
    'magnetic_detected': ('Sensors', 'magnetic_detected(port)',
                          'True if the magnetic sensor detects a field.'),
    'get_sound_volume': ('Sensors', 'get_sound_volume(port)',
                         'Sound volume level from the microphone port.'),
    'color_value': ('Sensors', 'color_value(port)',
                    'Raw color sensor reading (color number).'),
    'color_detected': ('Sensors', 'color_detected(port, color)',
                       'True if the color sensor sees color_red, '
                       'color_green, ...'),
    'get_digital_input': ('IO', 'get_digital_input(port)',
                          'Read a digital input bit.'),
    'get_analog_input': ('IO', 'get_analog_input(port)',
                         'Read a raw analog value.'),
    'set_digital_output': ('IO', 'set_digital_output(port, state)',
                           'Drive a digital output.'),
    'read_EEPROM': ('IO', 'read_EEPROM(address)', 'Read stored value.'),
    'write_EEPROM': ('IO', 'write_EEPROM(address, value)',
                     'Store a value (persists across reboots).'),
    'get_bt_remote_control': ('Sensors', 'get_bt_remote_control()',
                              'Bluetooth remote bitmask (advanced; bits are '
                              'vendor-defined).'),
    'button_pressed': ('Sensors', 'button_pressed(key)',
                       'True while a controller key is held (key_enter, '
                       'key_left, key_right).'),
    # servos
    'set_servo_angle': ('Servos', 'set_servo_angle(servo, speed, angle)',
                        'Move a servo (S1..S18) to an angle at a speed.'),
    'set_servo_rotation': ('Servos', 'set_servo_rotation(servo, speed)',
                           'Rotate a servo continuously at a speed.'),
    'restore_torque': ('Servos', 'restore_torque()',
                       'Re-enable servo torque (after it was released).'),
    # AI (other modules)
    'get_AI_image': ('AI', 'get_AI_image(port)',
                     'AI camera image ID (needs an AI-camera module; not '
                     'available on the MC101s).'),
    'get_AI_voice': ('AI', 'get_AI_voice()',
                     'AI voice command ID (needs an AI-voice module; not '
                     'available on the MC101s).'),
    # patrol / line following
    'patrol_integrated_initialization': ('Patrol',
                                         'patrol_integrated_initialization(lm,'
                                         ' ls, rm, rs)',
                                         'Start line following with the '
                                         '5-in-1 grayscale: left motor+speed,'
                                         ' right motor+speed.'),
    'patrol_single_initialization': ('Patrol',
                                     'patrol_single_initialization(lm, ls, '
                                     'rm, rs, p1..p5)',
                                     'Line following with 5 single '
                                     'grayscale sensors on ports P1..P5.'),
    'patrol_omni_wheel_integrated_init': ('Patrol',
                                          'patrol_omni_wheel_integrated_init('
                                          'a, b, c, d)',
                                          'Line following on the omni base '
                                          'with the 5-in-1 sensor.'),
    'patrol_omni_wheel_single_init': ('Patrol',
                                      'patrol_omni_wheel_single_init(a, b, '
                                      'c, d, p1..p5)',
                                      'Line following on the omni base with '
                                      '5 single sensors.'),
    'patrol_ambient_detection': ('Patrol', 'patrol_ambient_detection()',
                                 'Calibrate line following to ambient '
                                 'light.'),
    'patrol_speed': ('Patrol', 'patrol_speed(speed)',
                     'Set the line-following speed.'),
    'patrol_time': ('Patrol', 'patrol_time(speed, seconds)',
                    'Follow the line for a time.'),
    'patrol_road': ('Patrol', 'patrol_road(intersection, speed, seconds)',
                    'Handle a crossing: intersection_left, intersection_T, '
                    'intersection_right.'),
    'patrol_turn': ('Patrol', 'patrol_turn(turn, left_speed, right_speed)',
                    'Turn off/onto the line: turn_left, turn_center, '
                    'turn_right.'),
    'start_motor_time': ('Patrol', 'start_motor_time(l, r, seconds)',
                         'Drive both wheels (line-follow mode) for a time.'),
    'start_motor_angle': ('Patrol', 'start_motor_angle(l, r, degrees)',
                          'Drive both wheels by angle.'),
    'start_motor_sensor': ('Patrol', 'start_motor_sensor(l, r, port, cmp, v)',
                           'Drive until a port reading crosses a threshold '
                           '(compare_less_than, ...).'),
    'patrol_button': ('Patrol', 'patrol_button()',
                      'Wait for the start button.'),
    # timers / numbers
    'sleep': ('Timing', 'sleep(milliseconds)', 'Pause the program.'),
    'wait': ('Timing', 'wait(milliseconds)',
             'Pause the program (alias for sleep).'),
    'vTaskDelay': ('Timing', 'vTaskDelay(ticks)', 'Pause by OS ticks '
                   '(1 tick = 1 ms).'),
    'timer': ('Timing', 'timer()', 'Seconds since boot (or since reset).'),
    'reset_timer': ('Timing', 'reset_timer()', 'Restart the timer at 0.'),
    'random_number': ('Numbers', 'random_number(min, max)',
                      'Random whole number between min and max.'),
    'math_modulus': ('Numbers', 'math_modulus(a, b)', 'Remainder of a / b.'),
}


# ---- Device-object sugar layer ---------------------------------------------
# Device objects: a constructor call returns the port as an int handle;
# methods are thin aliases of the flat whale API ('h' = the handle, 'a0'/
# 'a1'/... = the method's own argument, in the flat function's own order
# and units). 'accepts' lists the flat API functions the handle may be
# passed to, with the handle-accepting argument positions.
SUGAR_DEVICES = {
    'Motor': {
        'accepts': {'set_motor': (0,), 'set_motor_time': (0,),
                    'set_motor_angle': (0,), 'off_motor': (0,),
                    'reverse_motor': (0,), 'get_motor_speed': (0,),
                    'get_encoder_value': (0,), 'reset_motor_encoder': (0,),
                    'set_dual_motor_time': (0, 2),
                    'set_dual_motor_angle': (0, 2)},
        'methods': {
            'set': {'api': 'set_motor', 'args': ['h', 'a0'],
                    'kw': ['speed']},
            'set_time': {'api': 'set_motor_time',
                         'args': ['h', 'a0', 'a1'],
                         'kw': ['speed', 'seconds']},
            'set_angle': {'api': 'set_motor_angle',
                          'args': ['h', 'a0', 'a1'],
                          'kw': ['speed', 'degrees']},
            'off': {'api': 'off_motor', 'args': ['h'], 'kw': []},
            'reverse': {'api': 'reverse_motor', 'args': ['h'], 'kw': []},
            'speed': {'api': 'get_motor_speed', 'args': ['h'], 'kw': []},
            'angle': {'api': 'get_encoder_value', 'args': ['h'], 'kw': []},
            'reset_angle': {'api': 'reset_motor_encoder', 'args': ['h'],
                            'kw': []},
        },
    },
    'TouchSensor': {
        'accepts': {'touch_switch_pressed': (0,)},
        'methods': {'pressed': {'api': 'touch_switch_pressed',
                                'args': ['h'], 'kw': []}},
    },
    'InfraredSensor': {
        'accepts': {'get_infrared_distance': (0,),
                    'obstacle_infrared_detected': (0,)},
        'methods': {'value': {'api': 'get_infrared_distance',
                              'args': ['h'], 'kw': []},
                    'obstacle': {'api': 'obstacle_infrared_detected',
                                 'args': ['h'], 'kw': []}},
    },
    'ColorSensor': {
        'accepts': {'color_value': (0,), 'color_detected': (0,)},
        'methods': {'value': {'api': 'color_value', 'args': ['h'], 'kw': []},
                    'detected': {'api': 'color_detected',
                                 'args': ['h', 'a0'], 'kw': ['color']}},
    },
    'UltrasonicSensor': {
        'accepts': {'get_ultrasonic_distance': (0,)},
        'methods': {'value': {'api': 'get_ultrasonic_distance',
                              'args': ['h'], 'kw': []}},
    },
    'SoundSensor': {
        'accepts': {'get_sound_volume': (0,)},
        'methods': {'value': {'api': 'get_sound_volume', 'args': ['h'],
                              'kw': []}},
    },
}

BUILTINS = {'abs': 1, 'min': 2, 'max': 2}   # always available, no import

# Keyword-argument names for every API function, taken from the signatures
# in API_HELP (the authoritative arity twin of API_FUNCS).
def _kw_from_sig(sig):
    toks = [p.strip() for p in
            sig[sig.index('(') + 1:sig.rindex(')')].split(',')]
    toks = [t for t in toks if t]
    names = []
    i = 0
    while i < len(toks):
        t = toks[i]
        m1 = re.fullmatch(r'([A-Za-z_]+)(\d+)', t)
        if i + 2 < len(toks) and toks[i + 1] == '...':
            m2 = re.fullmatch(r'([A-Za-z_]+)(\d+)', toks[i + 2])
            if m1 and m2 and m1.group(1) == m2.group(1):
                names += ['%s%d' % (m1.group(1), n)
                          for n in range(int(m1.group(2)),
                                         int(m2.group(2)) + 1)]
                i += 3
                continue
        m3 = re.fullmatch(r'([A-Za-z_]+)(\d+)\.\.([A-Za-z_]+)(\d+)', t)
        if m3 and m3.group(1) == m3.group(3):
            names += ['%s%d' % (m3.group(1), n)
                      for n in range(int(m3.group(2)), int(m3.group(4)) + 1)]
        elif re.fullmatch(r'[A-Za-z_][A-Za-z0-9_]*', t):
            names.append(t)
        i += 1
    return names


API_KW = {n: _kw_from_sig(API_HELP[n][1]) for n in API_FUNCS}
for _n, (_k, _r) in API_FUNCS.items():
    assert len(API_KW[_n]) == len(_k), (_n, API_HELP[_n][1])


class TranspileError(Exception):
    def __init__(self, msg, lineno=None):
        self.msg = msg
        self.lineno = lineno
        super().__init__(f'line {lineno}: {msg}' if lineno else msg)


class Func:
    def __init__(self, node, cname, is_entry):
        self.node = node
        self.cname = cname
        self.is_entry = is_entry
        self.params = [a.arg for a in node.args.args]
        self.param_types = {p: None for p in self.params}
        self.vars = {}          # local name -> 'int' | 'float'
        self.objvars = {}       # local name -> device class (handle tag)
        self.ret_type = None
        self.body = node.body


ENTRY_NAMES = ('main', 'user_main')

_TASK_RE = re.compile(r'^(?:task|user_task)(\d*)$')


def task_cname(name):
    """Map a Python entry def name to its C task name, or None.

    task / task1 / user_task1 -> user_task1 ... task15 / user_task15 ->
    user_task15 (the runtime supports up to 15 user tasks).
    """
    m = _TASK_RE.match(name)
    if not m:
        return None
    n = m.group(1)
    n = '1' if n == '' else n
    i = int(n)
    if not 1 <= i <= 15:
        return None
    return 'user_task%d' % i


class Transpiler:
    def __init__(self, tree, target='c'):
        self.tree = tree
        self.target = target    # 'c' | 'js'
        self.imported = {}      # py name -> device API name
        self.funcs = {}         # def name -> Func
        self.order = []
        self.entry_main = None
        self.entry_task = None
        self.c_helpers = set()  # math helpers to emit (C target)

    # ---- pass 0: imports + function collection ------------------------------
    @staticmethod
    def _strip_docstring(stmts):
        """Drop a leading string-literal docstring (module or function)."""
        if stmts and isinstance(stmts[0], ast.Expr) and \
                isinstance(stmts[0].value, ast.Constant) and \
                isinstance(stmts[0].value.value, str):
            return stmts[1:]
        return stmts

    def collect(self):
        self.tree.body = self._strip_docstring(self.tree.body)
        for node in self.tree.body:
            if isinstance(node, ast.ImportFrom):
                if node.module not in DIALECT_MODULES or node.level:
                    raise TranspileError(
                        "only 'from %s import ...' is supported"
                        % DIALECT_DOC, node.lineno)
                for alias in node.names:
                    if alias.name == '*':
                        raise TranspileError(
                            'star imports are not allowed — import exactly '
                            'what you use, e.g. from %s import A, '
                            'set_motor' % DIALECT_DOC, node.lineno)
                    src = alias.name
                    if src not in API_FUNCS and src not in API_CONSTS and \
                            src not in SUGAR_DEVICES:
                        raise TranspileError(
                            f"the device API has no '{src}' — see the API "
                            'help panel for the full list', node.lineno)
                    self.imported[alias.asname or alias.name] = src
                continue
            if isinstance(node, ast.Import):
                raise TranspileError(
                    "plain import is not supported; use "
                    "'from %s import ...'" % DIALECT_DOC, node.lineno)
            if isinstance(node, ast.FunctionDef):
                node.body = self._strip_docstring(node.body)
                self._check_sig(node)
                if node.name in ('main', 'user_main'):
                    f = Func(node, 'user_main', True)
                    if self.entry_main:
                        raise TranspileError('duplicate main()', node.lineno)
                    self.entry_main = f
                else:
                    cname = task_cname(node.name)
                    if cname:
                        f = Func(node, cname, True)
                        if any(x.cname == cname
                               for x in self.funcs.values()):
                            raise TranspileError(
                                f'duplicate {node.name}()', node.lineno)
                        self.entry_task = self.entry_task or f
                    else:
                        if node.name in API_FUNCS or node.name in \
                                API_CONSTS or node.name in SUGAR_DEVICES or \
                                node.name in BUILTINS:
                            raise TranspileError(
                                f"'{node.name}' is a device API name and "
                                'cannot be redefined', node.lineno)
                        f = Func(node, node.name, False)
                if f.is_entry and f.params:
                    raise TranspileError(
                        f"'{node.name}()' must take no parameters",
                        node.lineno)
                self.funcs[node.name] = f
                self.order.append(node.name)
            else:
                raise TranspileError(
                    'only imports and def statements are allowed at the '
                    'top level', node.lineno)
        if self.entry_main is None:
            raise TranspileError("program needs a 'def main():' entry point")

    @staticmethod
    def _check_sig(node):
        a = node.args
        bad = a.posonlyargs or a.kwonlyargs or a.vararg or a.kwarg or \
            a.defaults or a.kw_defaults
        if bad:
            raise TranspileError(
                f"function '{node.name}': only plain positional parameters "
                'are supported', node.lineno)
        if node.decorator_list:
            raise TranspileError(
                f"function '{node.name}': decorators are not supported",
                node.lineno)

    # ---- expression typing ---------------------------------------------------
    def etype(self, f, node, depth=0):
        if depth > 40:
            raise TranspileError('expression too deeply nested', node.lineno)
        if isinstance(node, ast.Constant):
            v = node.value
            if isinstance(v, bool):
                return 'int'
            if isinstance(v, int):
                return 'int'
            if isinstance(v, float):
                return 'float'
            raise TranspileError(
                f'unsupported literal {v!r} (strings and other objects are '
                'not supported by the device API)', node.lineno)
        if isinstance(node, ast.Name):
            if node.id in f.vars or node.id in f.param_types:
                return f.vars.get(node.id) or f.param_types.get(node.id) \
                    or 'int'
            if self.imported.get(node.id) in API_CONSTS:
                return 'int'
            hint = '' if node.id in self.imported else \
                " — did you forget 'from %s import ...'?" % DIALECT_DOC
            raise TranspileError(f"unknown name '{node.id}'{hint}",
                                 node.lineno)
        if isinstance(node, ast.Attribute):
            self.bad_attribute(f, node)   # always raises
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            self._no_handle(f, node.operand)
            return self.etype(f, node.operand, depth + 1)
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Div):
                self._no_handle(f, node.left)
                self._no_handle(f, node.right)
                return 'float'
            if isinstance(node.op, ast.Pow):
                raise TranspileError("'**' is not supported (use repeated "
                                     'multiplication)', node.lineno)
            self._no_handle(f, node.left)
            self._no_handle(f, node.right)
            lt = self.etype(f, node.left, depth + 1)
            rt = self.etype(f, node.right, depth + 1)
            return 'float' if 'float' in (lt, rt) else 'int'
        if isinstance(node, ast.BoolOp) or isinstance(node, ast.Compare):
            for sub in self._iter_exprs(node):
                self._no_handle(f, sub)
                self.etype(f, sub, depth + 1)
            return 'int'
        if isinstance(node, ast.Call):
            kind, tgt, _ = self.call_target(f, node)
            if kind == 'api':
                return 'float' if API_FUNCS[tgt][1] == 'f' else 'int'
            if kind == 'builtin':
                return 'float'
            if kind == 'method':
                return 'float' if API_FUNCS[SUGAR_DEVICES[tgt[0]]
                                            ['methods'][tgt[1]]['api']][1] \
                    == 'f' else 'int'
            if kind == 'ctor':
                return 'int'
            return self.funcs[tgt].ret_type or 'int'
        raise TranspileError(
            f'unsupported expression ({type(node).__name__})', node.lineno)

    @staticmethod
    def _no_handle(f, node):
        if isinstance(node, ast.Name) and node.id in f.objvars:
            raise TranspileError(
                f"cannot use device object '{node.id}' in arithmetic or "
                'conditions — call its methods instead', node.lineno)

    def bad_attribute(self, f, node):
        if isinstance(node.value, ast.Name):
            v = node.value.id
            if v in f.objvars:
                raise TranspileError(
                    f"device object '{v}' ({f.objvars[v]}) only supports "
                    'method calls', node.lineno)
            raise TranspileError(
                f"unsupported attribute '{node.attr}' on '{v}' — attribute "
                'access is not part of the whale dialect', node.lineno)
        raise TranspileError('unsupported attribute access', node.lineno)

    @staticmethod
    def _iter_exprs(node):
        if isinstance(node, ast.BoolOp):
            for v in node.values:
                yield from Transpiler._iter_exprs(v)
        elif isinstance(node, ast.Compare):
            yield node.left
            for c in node.comparators:
                yield from Transpiler._iter_exprs(c)
        else:
            yield node

    def call_target(self, f, node):
        if isinstance(node.func, ast.Attribute):
            return self.method_target(f, node)
        if not isinstance(node.func, ast.Name):
            raise TranspileError('only plain function calls are supported',
                                 node.lineno)
        name = node.func.id
        if name in BUILTINS:
            return 'builtin', name, name
        src = self.imported.get(name, name)
        if src in API_FUNCS:
            return 'api', src, src
        if src in SUGAR_DEVICES:
            return 'ctor', src, src
        if src in self.funcs and src not in ENTRY_NAMES:
            return 'user', src, src
        hint = " — did you forget 'from %s import ...'?" \
            % DIALECT_DOC if name not in self.imported else ''
        raise TranspileError(f"unknown function '{name}'{hint}", node.lineno)

    def method_target(self, f, node):
        recv = node.func.value
        meth = node.func.attr
        if not isinstance(recv, ast.Name):
            raise TranspileError(
                'only simple device objects support method calls',
                node.lineno)
        cls = f.objvars.get(recv.id)
        if cls is None:
            raise TranspileError(
                f"unsupported object '{recv.id}' for method calls — device "
                'objects are created with a constructor like Motor(A)',
                node.lineno)
        if meth not in SUGAR_DEVICES[cls]['methods']:
            raise TranspileError(
                f"'{cls}' object has no method '{meth}'()", node.lineno)
        return 'method', (cls, meth), cls

    @staticmethod
    def norm_args(what, node, arity, kw_names):
        """Merge positional + keyword args against a known signature.
        kw_names may contain None for slots that cannot be passed by
        name (the desugared device-handle slot)."""
        pos = list(node.args)
        pos_slots = [i for i in range(arity) if kw_names[i]]
        if len(pos) > len(pos_slots):
            raise TranspileError(
                f'{what}() takes {len(pos_slots)} argument(s), got '
                f'{len(pos) + len(node.keywords)}', node.lineno)
        slots = [None] * arity
        for a, i in zip(pos, pos_slots):
            slots[i] = a
        named = [n for n in kw_names if n]
        for kw in node.keywords:
            if kw.arg is None:
                raise TranspileError(f'{what}() does not accept **kwargs',
                                     node.lineno)
            if kw.arg not in named:
                raise TranspileError(
                    f"unknown argument '{kw.arg}' for {what}() — expected "
                    'one of: ' + ', '.join(named), node.lineno)
            i = kw_names.index(kw.arg)
            if slots[i] is not None:
                raise TranspileError(
                    f"argument '{kw.arg}' given twice in {what}() call",
                    node.lineno)
            slots[i] = kw.value
        missing = [kw_names[i] for i in range(arity)
                   if slots[i] is None and kw_names[i]]
        if missing:
            raise TranspileError(
                f'{what}() takes {len(pos_slots)} argument(s), got '
                f'{len(pos) + len(node.keywords)}', node.lineno)
        return slots

    def method_slots(self, f, recv, m, slots, lineno):
        """Map a method's merged args through the desugar table."""
        hpos = {i for i, s in enumerate(m['args']) if s == 'h'}
        ownl = [s for i, s in enumerate(slots) if i not in hpos]
        own = {'a%d' % i: a for i, a in enumerate(ownl)}
        out = []
        for spec in m['args']:
            if spec == 'h':
                out.append(ast.Name(id=recv, ctx=ast.Load()))
            else:
                out.append(own[spec])
        return out

    # ---- inference pass ------------------------------------------------------
    def infer_signatures(self):
        # Two rounds: call-site float args upgrade params (round 1), which
        # can upgrade return types, which can upgrade more params (round 2).
        for _ in range(2):
            for name in self.order:
                f = self.funcs[name]
                has_ret = False
                for node in ast.walk(f.node):
                    if isinstance(node, ast.Return) and node.value is not None:
                        has_ret = True
                        try:
                            ty = self.etype(f, node.value)
                        except TranspileError:
                            continue
                        f.ret_type = ty if f.ret_type is None else \
                            ('float' if 'float' in (ty, f.ret_type) else 'int')
                if has_ret and f.ret_type is None:
                    f.ret_type = 'int'
                if not has_ret:
                    f.ret_type = 'void'
            for name in self.order:
                f = self.funcs[name]
                for node in ast.walk(f.node):
                    if isinstance(node, ast.Call):
                        try:
                            kind, tgt, _ = self.call_target(f, node)
                        except TranspileError:
                            continue
                        if kind != 'user':
                            continue
                        uf = self.funcs[tgt]
                        if len(node.args) == len(uf.params):
                            for p, a in zip(uf.params, node.args):
                                try:
                                    if self.etype(f, a) == 'float':
                                        uf.param_types[p] = 'float'
                                except TranspileError:
                                    pass

    @staticmethod
    def _stmt_tree(stmts):
        for st in stmts:
            yield st
            yield from Transpiler._stmt_tree(getattr(st, 'body', []) or [])
            yield from Transpiler._stmt_tree(getattr(st, 'orelse', []) or [])

    def settle_vars(self, f):
        """Register local declarations + upgrade int->float (two ordered
        passes so `x = 1; x = x / 2` ends up float). Source order, so the
        emitted declaration order is stable for both backends."""
        for _ in range(2):
            for node in self._stmt_tree(f.body):
                if isinstance(node, ast.Assign) and \
                        isinstance(node.targets[0], ast.Name):
                    name = node.targets[0].id
                    if name in f.param_types or name in self.imported:
                        continue
                    try:
                        ty = self.etype(f, node.value)
                    except TranspileError:
                        continue
                    cur = f.vars.get(name)
                    f.vars[name] = 'float' if 'float' in (cur, ty) else 'int'
                elif isinstance(node, ast.AugAssign) and \
                        isinstance(node.target, ast.Name):
                    name = node.target.id
                    if name in f.param_types or name in self.imported:
                        continue
                    if isinstance(node.op, ast.Div):
                        f.vars[name] = 'float'
                elif isinstance(node, ast.For) and \
                        isinstance(node.target, ast.Name):
                    if node.target.id not in f.param_types and \
                            node.target.id not in self.imported:
                        f.vars.setdefault(node.target.id, 'int')

    def tag_objects(self, f):
        """Track which locals hold a device-object handle (type tag)."""
        for node in self._stmt_tree(f.body):
            if not (isinstance(node, ast.Assign) and
                    len(node.targets) == 1 and
                    isinstance(node.targets[0], ast.Name)):
                continue
            name = node.targets[0].id
            if name in f.param_types or name in self.imported:
                continue
            v = node.value
            if isinstance(v, ast.Call) and isinstance(v.func, ast.Name) and \
                    self.imported.get(v.func.id) in SUGAR_DEVICES:
                f.objvars[name] = self.imported[v.func.id]
            elif isinstance(v, ast.Name) and v.id in f.objvars:
                f.objvars[name] = f.objvars[v.id]
            else:
                f.objvars.pop(name, None)

    # ---- emission ------------------------------------------------------------
    def emit(self):
        if self.target == 'js':
            return self.emit_js()
        out = [GPL_HEADER]
        body = []
        protos = []
        for name in self.order:
            f = self.funcs[name]
            self.settle_vars(f)
            if not f.is_entry:
                ps = ', '.join(
                    f"{'float' if f.param_types[p] == 'float' else 'int'} {p}"
                    for p in f.params)
                protos.append(f'static {f.ret_type or "void"} {f.cname}'
                              f'({ps or "void"});')
        for name in self.order:
            f = self.funcs[name]
            self.emit_func(f, body)
        # math helpers are collected while emitting the calls above
        if 'abs' in self.c_helpers:
            out.append('static float whale_fabs(float x) '
                       '{ return x < 0 ? -x : x; }')
        if 'min' in self.c_helpers:
            out.append('static float whale_fmin(float a, float b) '
                       '{ return a < b ? a : b; }')
        if 'max' in self.c_helpers:
            out.append('static float whale_fmax(float a, float b) '
                       '{ return a > b ? a : b; }')
        if self.c_helpers:
            out.append('')
        out.extend(protos)
        if protos:
            out.append('')
        out.extend(body)
        return '\n'.join(out) + '\n'

    def emit_func(self, f, out):
        if f.is_entry:
            sig = f'void {f.cname}(void)'
        else:
            ps = ', '.join(
                f"{'float' if f.param_types[p] == 'float' else 'int'} {p}"
                for p in f.params)
            sig = f'static {f.ret_type or "void"} {f.cname}({ps or "void"})'
        out.append(sig + ' {')
        for name, ty in f.vars.items():
            if name not in f.param_types:
                out.append(f'    {ty} {name};')
        self.emit_block(f, f.body, out, 1)
        out.append('}')
        out.append('')

    def emit_block(self, f, stmts, out, ind):
        for st in stmts:
            self.emit_stmt(f, st, out, ind)

    def emit_stmt(self, f, st, out, ind):
        pad = '    ' * ind
        if isinstance(st, ast.Pass):
            out.append(pad + ';')
            return
        if isinstance(st, ast.Expr):
            if not isinstance(st.value, ast.Call):
                raise TranspileError('expression statements must be calls',
                                     st.lineno)
            call = self.emit_call(f, st.value)
            out.append(pad + (call if call.endswith('}') else call + ';'))
            return
        if isinstance(st, ast.Assign):
            if len(st.targets) != 1 or not isinstance(st.targets[0],
                                                      ast.Name):
                raise TranspileError(
                    'only single simple-name assignments are supported',
                    st.lineno)
            name = st.targets[0].id
            if name in self.imported:
                raise TranspileError(
                    f"cannot assign to imported name '{name}' — pick a "
                    'different variable name', st.lineno)
            ty = self.etype(f, st.value)
            rhs = self.emit_expr(f, st.value)
            if name in f.param_types:
                pty = f.param_types[name] or 'int'
                if pty == 'int' and ty == 'float':
                    rhs = f'(int)({rhs})'
                out.append(f'{pad}{name} = {rhs};')
            else:
                decl = f.vars.get(name, 'int')
                cast = '(int) ' if (decl == 'int' and ty == 'float') else ''
                out.append(f'{pad}{name} = {cast}{rhs};')
            return
        if isinstance(st, ast.AugAssign):
            if not isinstance(st.target, ast.Name):
                raise TranspileError(
                    'augmented assignment target must be a simple name',
                    st.lineno)
            name = st.target.id
            if name in f.objvars:
                raise TranspileError(
                    f"cannot use augmented assignment on device object "
                    f"'{name}'", st.lineno)
            if name in self.imported:
                raise TranspileError(
                    f"cannot assign to imported name '{name}'", st.lineno)
            if name not in f.vars and name not in f.param_types:
                raise TranspileError(
                    f"unknown name '{name}' — assign it before using "
                    '+=/-= etc.', st.lineno)
            rhs = self.emit_expr(f, st.value)
            if isinstance(st.op, ast.Div):
                out.append(f'{pad}{name} = (float)({name}) / ({rhs});')
                if name in f.vars:
                    f.vars[name] = 'float'
            else:
                op = BINOPS[type(st.op)]
                out.append(f'{pad}{name} = {name} {op} ({rhs});')
            return
        if isinstance(st, ast.If):
            self.emit_if(f, st, out, ind)
            return
        if isinstance(st, ast.While):
            out.append(pad + f'while ({self.emit_expr(f, st.test)}) {{')
            self.emit_block(f, st.body, out, ind + 1)
            out.append(pad + '}')
            return
        if isinstance(st, ast.For):
            self.emit_for(f, st, out, ind)
            return
        if isinstance(st, (ast.Break, ast.Continue)):
            out.append(pad + ('break;' if isinstance(st, ast.Break)
                              else 'continue;'))
            return
        if isinstance(st, ast.Return):
            if st.value is None:
                out.append(pad + 'return;')
                return
            ty = self.etype(f, st.value)
            ret = f.ret_type or ty
            rhs = self.emit_expr(f, st.value)
            cast = '(int) ' if (ret == 'int' and ty == 'float') else ''
            out.append(pad + f'return {cast}{rhs};')
            return
        if isinstance(st, (ast.Import, ast.ImportFrom)):
            raise TranspileError('imports must be at the top of the file',
                                 st.lineno)
        raise TranspileError(f'unsupported statement ({type(st).__name__})',
                             st.lineno)

    def emit_if(self, f, st, out, ind):
        pad = '    ' * ind
        out.append(pad + f'if ({self.emit_expr(f, st.test)}) {{')
        self.emit_block(f, st.body, out, ind + 1)
        orelse = st.orelse
        while orelse:
            if len(orelse) == 1 and isinstance(orelse[0], ast.If):
                n = orelse[0]
                out.append(pad + '} else if ('
                           f'{self.emit_expr(f, n.test)}) ' + '{')
                self.emit_block(f, n.body, out, ind + 1)
                orelse = n.orelse
            else:
                out.append(pad + '} else {')
                self.emit_block(f, orelse, out, ind + 1)
                orelse = None
        out.append(pad + '}')

    def emit_for(self, f, st, out, ind):
        pad = '    ' * ind
        it = st.iter
        if not (isinstance(it, ast.Call) and isinstance(it.func, ast.Name)
                and it.func.id == 'range' and not it.keywords):
            raise TranspileError('only for-in-range loops are supported',
                                 st.lineno)
        if len(it.args) not in (2, 3):
            raise TranspileError('range() needs range(a, b) or '
                                 'range(a, b, step)', st.lineno)
        if not isinstance(st.target, ast.Name):
            raise TranspileError('for-loop target must be a simple name',
                                 st.lineno)
        i = st.target.id
        if i in self.imported:
            raise TranspileError(
                f"cannot use imported name '{i}' as a loop variable",
                st.lineno)
        if i in f.objvars:
            raise TranspileError(
                f"cannot use device object '{i}' as a loop variable",
                st.lineno)
        if i in f.param_types:
            raise TranspileError(
                f"for-loop variable '{i}' shadows a parameter", st.lineno)
        f.vars[i] = 'int'
        start = self.cexpr_int(f, it.args[0])
        stop = self.cexpr_int(f, it.args[1])
        if len(it.args) == 3:
            step = it.args[2]
            neg = False
            if isinstance(step, ast.UnaryOp) and \
                    isinstance(step.op, ast.USub):
                neg = True
                step = step.operand
            if not (isinstance(step, ast.Constant)
                    and isinstance(step.value, int)
                    and not isinstance(step.value, bool)
                    and step.value != 0):
                raise TranspileError(
                    'range() step must be a non-zero whole number',
                    st.lineno)
            s = -step.value if neg else step.value
            cmp = '>' if s < 0 else '<'
            out.append(pad + f'for ({i} = {start}; {i} {cmp} {stop}; '
                       f'{i} += {s}) {{')
        else:
            out.append(pad + f'for ({i} = {start}; {i} < {stop}; {i}++) {{')
        self.emit_block(f, st.body, out, ind + 1)
        out.append(pad + '}')

    def cexpr_int(self, f, node):
        if self.target == 'js':
            s = self.emit_js_expr(f, node)
        else:
            s = self.emit_expr(f, node)
        return f'(int)({s})' if (self.target != 'js' and
                                 self.etype(f, node) == 'float') else s

    # ---- expressions ---------------------------------------------------------
    def emit_expr(self, f, node, prec=0):
        if isinstance(node, ast.Constant):
            v = node.value
            if isinstance(v, bool):
                return '1' if v else '0'
            return repr(v)
        if isinstance(node, ast.Name):
            if node.id in f.vars or node.id in f.param_types:
                return node.id
            src = self.imported.get(node.id, node.id)
            if src in API_CONSTS:
                return src
            return node.id
        if isinstance(node, ast.Attribute):
            self.bad_attribute(f, node)   # always raises
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            s = '-' + self.emit_expr(f, node.operand, 3)
            return f'({s})' if prec > 2 else s
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
            return f'(!{self.emit_expr(f, node.operand, 3)})'
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Pow):
                raise TranspileError("'**' is not supported", node.lineno)
            if isinstance(node.op, ast.Div):
                return (f'((float)({self.emit_expr(f, node.left, 2)}) / '
                        f'(float)({self.emit_expr(f, node.right, 2)}))')
            op = BINOPS[type(node.op)]
            s = f'{self.emit_expr(f, node.left, 2)} {op} ' \
                f'{self.emit_expr(f, node.right, 2)}'
            return f'({s})' if prec > 1 else s
        if isinstance(node, ast.BoolOp):
            op = ' && ' if isinstance(node.op, ast.And) else ' || '
            return '(' + op.join(self.emit_expr(f, v, 1)
                                 for v in node.values) + ')'
        if isinstance(node, ast.Compare):
            if len(node.ops) == 1:
                sym = CMPOPS.get(type(node.ops[0]))
                if sym is None:
                    raise TranspileError('unsupported comparison',
                                         node.lineno)
                return (f'({self.emit_expr(f, node.left, 2)} {sym} '
                        f'{self.emit_expr(f, node.comparators[0], 2)})')
            # chained comparison: C would mis-evaluate a < b < c; emit
            # Python semantics as (a < b) && (b < c)
            parts = []
            left = node.left
            for op, cmp in zip(node.ops, node.comparators):
                sym = CMPOPS.get(type(op))
                if sym is None:
                    raise TranspileError('unsupported comparison',
                                         node.lineno)
                parts.append(f'({self.emit_expr(f, left, 2)} {sym} '
                             f'{self.emit_expr(f, cmp, 2)})')
                left = cmp
            return '(' + ' && '.join(parts) + ')'
        if isinstance(node, ast.Call):
            return self.emit_call(f, node)
        raise TranspileError(f'unsupported expression ({type(node).__name__})',
                             node.lineno)

    def _check_handle_args(self, f, tgt, args, lineno):
        """Device handles may only go where the flat API accepts them."""
        for i, a in enumerate(args):
            if isinstance(a, ast.Name) and a.id in f.objvars:
                cls = f.objvars[a.id]
                pos = SUGAR_DEVICES[cls]['accepts'].get(tgt, ())
                if i not in pos:
                    raise TranspileError(
                        f"cannot pass a {cls} object to {tgt}() — pass a "
                        'port constant or number instead', lineno)

    def _call_parts(self, f, node):
        """kind/target plus the merged positional arg nodes for any call."""
        kind, tgt, _ = self.call_target(f, node)
        if kind == 'builtin':
            if node.keywords or len(node.args) != BUILTINS[tgt]:
                raise TranspileError(
                    f'{tgt}() takes {BUILTINS[tgt]} argument(s)',
                    node.lineno)
            return kind, tgt, list(node.args)
        if kind == 'ctor':
            if node.keywords or len(node.args) != 1:
                raise TranspileError(
                    f'{tgt}() takes exactly one port argument', node.lineno)
            a = node.args[0]
            if isinstance(a, ast.Name) and a.id in f.objvars:
                raise TranspileError(
                    f"cannot use a {f.objvars[a.id]} object as a port — "
                    'pass a port constant or a number', node.lineno)
            return kind, tgt, [a]
        if kind == 'method':
            cls, meth = tgt
            m = SUGAR_DEVICES[cls]['methods'][meth]
            api = m['api']
            kinds, _ = API_FUNCS[api]
            slots = self.norm_args(f'{cls}.{meth}', node, len(kinds),
                                   [None] + m['kw'])
            return 'api', api, \
                self.method_slots(f, node.func.value.id, m, slots,
                                  node.lineno)
        if kind == 'api':
            kinds, _ = API_FUNCS[tgt]
            return kind, tgt, self.norm_args(tgt, node, len(kinds),
                                             API_KW[tgt])
        if node.keywords:
            raise TranspileError(
                'keyword arguments are only supported for device API '
                'calls, not user functions', node.lineno)
        uf = self.funcs[tgt]
        if len(node.args) != len(uf.params):
            raise TranspileError(
                f'{tgt}() takes {len(uf.params)} argument(s), '
                f'got {len(node.args)}', node.lineno)
        return kind, tgt, list(node.args)

    def emit_api_call_c(self, f, tgt, args, lineno):
        kinds, _ = API_FUNCS[tgt]
        self._check_handle_args(f, tgt, args, lineno)
        cs = []
        for k, a in zip(kinds, args):
            s = self.emit_expr(f, a)
            aty = self.etype(f, a)
            if k == 'f' and aty == 'int':
                s = f'(float)({s})'
            elif k == 'i' and aty == 'float':
                s = f'(int)({s})'
            cs.append(s)
        if tgt == 'display_custom':
            # LedMaritx is the vendor struct { u8 data[8] } passed by
            # value; the dialect has no arrays, so the 8 row bitmasks
            # become one.
            port, rows = cs[0], cs[1:]
            return ('{ LedMaritx whale_matrix = {{%s}}; '
                    'display_custom(%s, whale_matrix); }'
                    % (', '.join(rows), port))
        name = 'vTaskDelay' if tgt in ('sleep', 'wait') else tgt
        return f'{name}({", ".join(cs)})'

    def emit_call(self, f, node):
        kind, tgt, args = self._call_parts(f, node)
        if kind == 'builtin':
            cs = [self.emit_expr(f, a) for a in args]
            self.c_helpers.add(tgt)
            name = {'abs': 'whale_fabs', 'min': 'whale_fmin',
                    'max': 'whale_fmax'}[tgt]
            return f'{name}({", ".join(cs)})'
        if kind == 'ctor':
            return self.emit_expr(f, args[0])
        if kind == 'api':
            return self.emit_api_call_c(f, tgt, args, node.lineno)
        cs = [self.emit_expr(f, a) for a in args]
        return f'{tgt}({", ".join(cs)})'


    # ---- JS emission (live over Bluetooth, run by js/whale_ble.js) -----------
    def emit_js(self):
        out = [JS_HEADER]
        for name in self.order:
            f = self.funcs[name]
            self.settle_vars(f)
            self.emit_js_func(f, out)
        return '\n'.join(out) + '\n'

    def emit_js_func(self, f, out):
        out.append(f'async function {f.cname}({", ".join(f.params)}) {{')
        for name in f.vars:
            if name not in f.param_types:
                out.append(f'    let {name};')
        if f.is_entry and f.cname != 'user_main':
            # tasks repeat until stopped, matching the C build where the
            # runtime loops each user_taskN
            out.append('    while (true) {')
            self.emit_js_block(f, f.body, out, 2)
            out.append('        if (whale.stopped) break;')
            out.append('    }')
        else:
            self.emit_js_block(f, f.body, out, 1)
        out.append('}')
        out.append('')

    def emit_js_block(self, f, stmts, out, ind):
        for st in stmts:
            self.emit_js_stmt(f, st, out, ind)

    def emit_js_stmt(self, f, st, out, ind):
        pad = '    ' * ind
        if isinstance(st, ast.Pass):
            out.append(pad + ';')
            return
        if isinstance(st, ast.Expr):
            if not isinstance(st.value, ast.Call):
                raise TranspileError('expression statements must be calls',
                                     st.lineno)
            out.append(pad + self.emit_js_call(f, st.value) + ';')
            return
        if isinstance(st, ast.Assign):
            if len(st.targets) != 1 or not isinstance(st.targets[0],
                                                      ast.Name):
                raise TranspileError(
                    'only single simple-name assignments are supported',
                    st.lineno)
            name = st.targets[0].id
            if name in self.imported:
                raise TranspileError(
                    f"cannot assign to imported name '{name}' — pick a "
                    'different variable name', st.lineno)
            self.etype(f, st.value)    # validate before emitting
            out.append(f'{pad}{name} = '
                       f'{self.emit_js_expr(f, st.value)};')
            return
        if isinstance(st, ast.AugAssign):
            if not isinstance(st.target, ast.Name):
                raise TranspileError(
                    'augmented assignment target must be a simple name',
                    st.lineno)
            name = st.target.id
            if name in f.objvars:
                raise TranspileError(
                    f"cannot use augmented assignment on device object "
                    f"'{name}'", st.lineno)
            if name in self.imported:
                raise TranspileError(
                    f"cannot assign to imported name '{name}'", st.lineno)
            if name not in f.vars and name not in f.param_types:
                raise TranspileError(
                    f"unknown name '{name}' — assign it before using "
                    '+=/-= etc.', st.lineno)
            rhs = self.emit_js_expr(f, st.value)
            if isinstance(st.op, ast.Div):
                out.append(f'{pad}{name} /= {rhs};')
            elif isinstance(st.op, ast.FloorDiv):
                out.append(f'{pad}{name} = Math.floor({name} / {rhs});')
            elif isinstance(st.op, ast.Mod):
                out.append(f'{pad}{name} = whale.mod({name}, {rhs});')
            else:
                op = BINOPS[type(st.op)]
                out.append(f'{pad}{name} {op}= {rhs};')
            return
        if isinstance(st, ast.If):
            self.emit_js_if(f, st, out, ind)
            return
        if isinstance(st, ast.While):
            out.append(pad + f'while ({self.emit_js_expr(f, st.test)}) {{')
            self.emit_js_block(f, st.body, out, ind + 1)
            out.append(pad + '}')
            return
        if isinstance(st, ast.For):
            self.emit_js_for(f, st, out, ind)
            return
        if isinstance(st, (ast.Break, ast.Continue)):
            out.append(pad + ('break;' if isinstance(st, ast.Break)
                              else 'continue;'))
            return
        if isinstance(st, ast.Return):
            if st.value is None:
                out.append(pad + 'return;')
                return
            self.etype(f, st.value)    # validate before emitting
            out.append(pad + 'return '
                       f'{self.emit_js_expr(f, st.value)};')
            return
        if isinstance(st, (ast.Import, ast.ImportFrom)):
            raise TranspileError('imports must be at the top of the file',
                                 st.lineno)
        raise TranspileError(f'unsupported statement ({type(st).__name__})',
                             st.lineno)

    def emit_js_if(self, f, st, out, ind):
        pad = '    ' * ind
        out.append(pad + f'if ({self.emit_js_expr(f, st.test)}) {{')
        self.emit_js_block(f, st.body, out, ind + 1)
        orelse = st.orelse
        while orelse:
            if len(orelse) == 1 and isinstance(orelse[0], ast.If):
                n = orelse[0]
                out.append(pad + '} else if ('
                           f'{self.emit_js_expr(f, n.test)}) ' + '{')
                self.emit_js_block(f, n.body, out, ind + 1)
                orelse = n.orelse
            else:
                out.append(pad + '} else {')
                self.emit_js_block(f, orelse, out, ind + 1)
                orelse = None
        out.append(pad + '}')

    def emit_js_for(self, f, st, out, ind):
        pad = '    ' * ind
        it = st.iter
        if not (isinstance(it, ast.Call) and isinstance(it.func, ast.Name)
                and it.func.id == 'range' and not it.keywords):
            raise TranspileError('only for-in-range loops are supported',
                                 st.lineno)
        if len(it.args) not in (2, 3):
            raise TranspileError('range() needs range(a, b) or '
                                 'range(a, b, step)', st.lineno)
        if not isinstance(st.target, ast.Name):
            raise TranspileError('for-loop target must be a simple name',
                                 st.lineno)
        i = st.target.id
        if i in self.imported:
            raise TranspileError(
                f"cannot use imported name '{i}' as a loop variable",
                st.lineno)
        if i in f.objvars:
            raise TranspileError(
                f"cannot use device object '{i}' as a loop variable",
                st.lineno)
        if i in f.param_types:
            raise TranspileError(
                f"for-loop variable '{i}' shadows a parameter", st.lineno)
        f.vars[i] = 'int'
        start = self.cexpr_int(f, it.args[0])
        stop = self.cexpr_int(f, it.args[1])
        if len(it.args) == 3:
            step = it.args[2]
            neg = False
            if isinstance(step, ast.UnaryOp) and \
                    isinstance(step.op, ast.USub):
                neg = True
                step = step.operand
            if not (isinstance(step, ast.Constant)
                    and isinstance(step.value, int)
                    and not isinstance(step.value, bool)
                    and step.value != 0):
                raise TranspileError(
                    'range() step must be a non-zero whole number',
                    st.lineno)
            s = -step.value if neg else step.value
            cmp = '>' if s < 0 else '<'
            out.append(pad + f'for ({i} = {start}; {i} {cmp} {stop}; '
                       f'{i} += {s}) {{')
        else:
            out.append(pad + f'for ({i} = {start}; {i} < {stop}; {i}++) {{')
        self.emit_js_block(f, st.body, out, ind + 1)
        out.append(pad + '}')

    def emit_js_expr(self, f, node, prec=0):
        if isinstance(node, ast.Constant):
            v = node.value
            if isinstance(v, bool):
                return 'true' if v else 'false'
            return repr(v)
        if isinstance(node, ast.Name):
            if node.id in f.vars or node.id in f.param_types:
                return node.id
            src = self.imported.get(node.id, node.id)
            if src in API_CONSTS:
                return f'whale.{src}'
            return node.id
        if isinstance(node, ast.Attribute):
            self.bad_attribute(f, node)   # always raises
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.USub):
            s = '-' + self.emit_js_expr(f, node.operand, 3)
            return f'({s})' if prec > 2 else s
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
            return f'(!{self.emit_js_expr(f, node.operand, 3)})'
        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Pow):
                raise TranspileError("'**' is not supported", node.lineno)
            l = self.emit_js_expr(f, node.left, 2)
            r = self.emit_js_expr(f, node.right, 2)
            if isinstance(node.op, ast.Div):
                s = f'{l} / {r}'
            elif isinstance(node.op, ast.FloorDiv):
                s = f'Math.floor({l} / {r})'
            elif isinstance(node.op, ast.Mod):
                s = f'whale.mod({l}, {r})'
            else:
                s = f'{l} {BINOPS[type(node.op)]} {r}'
            return f'({s})' if prec > 1 else s
        if isinstance(node, ast.BoolOp):
            op = ' && ' if isinstance(node.op, ast.And) else ' || '
            return '(' + op.join(self.emit_js_expr(f, v, 1)
                                 for v in node.values) + ')'
        if isinstance(node, ast.Compare):
            if len(node.ops) == 1:
                sym = CMPOPS.get(type(node.ops[0]))
                if sym is None:
                    raise TranspileError('unsupported comparison',
                                         node.lineno)
                return (f'({self.emit_js_expr(f, node.left, 2)} {sym} '
                        f'{self.emit_js_expr(f, node.comparators[0], 2)})')
            # chained comparison: (a < b) && (b < c), as in the C backend
            parts = []
            left = node.left
            for op, cmp in zip(node.ops, node.comparators):
                sym = CMPOPS.get(type(op))
                if sym is None:
                    raise TranspileError('unsupported comparison',
                                         node.lineno)
                parts.append(f'({self.emit_js_expr(f, left, 2)} {sym} '
                             f'{self.emit_js_expr(f, cmp, 2)})')
                left = cmp
            return '(' + ' && '.join(parts) + ')'
        if isinstance(node, ast.Call):
            # API + user calls return promises; await them even inside
            # expressions (every emitted function is async)
            return self.emit_js_call(f, node)
        raise TranspileError(f'unsupported expression ({type(node).__name__})',
                             node.lineno)

    def emit_api_call_js(self, f, tgt, args, lineno):
        kinds, _ = API_FUNCS[tgt]
        self._check_handle_args(f, tgt, args, lineno)
        cs = []
        for k, a in zip(kinds, args):
            self.etype(f, a)    # same validation as the C backend
            cs.append(self.emit_js_expr(f, a))
        name = 'sleep' if tgt == 'wait' else tgt
        return f'await whale.{name}({", ".join(cs)})'

    def emit_js_call(self, f, node):
        kind, tgt, args = self._call_parts(f, node)
        if kind == 'builtin':
            cs = [self.emit_js_expr(f, a) for a in args]
            return f'Math.{tgt}({", ".join(cs)})'
        if kind == 'ctor':
            return self.emit_js_expr(f, args[0])
        if kind == 'api':
            return self.emit_api_call_js(f, tgt, args, node.lineno)
        cs = [self.emit_js_expr(f, a) for a in args]
        return f'await {tgt}({", ".join(cs)})'


def api_reference():
    """The device API as a list for the IDE help panel."""
    out = []
    for name, (cat, sig, desc) in API_HELP.items():
        out.append({'name': name, 'category': cat, 'signature': sig,
                    'description': desc})
    return sorted(out, key=lambda e: (e['category'], e['name']))


def dump_api():
    """Machine-readable export of everything the dialect knows: API
    functions (with keyword-argument names), constants, the help
    reference and the sugar-layer tables.  Consumed by the browser
    transpiler (static/js/whalepy.js) via the bundled api.json."""
    return {
        'funcs': {n: {'kinds': k, 'ret': r, 'kw': API_KW[n]}
                  for n, (k, r) in API_FUNCS.items()},
        'consts': list(API_CONSTS),
        'help': api_reference(),
        'sugar': {'devices': SUGAR_DEVICES, 'builtins': sorted(BUILTINS)},
        'js_header': JS_HEADER,
    }


def write_api_json(path):
    with open(path, 'w') as fh:
        json.dump(dump_api(), fh, indent=1, sort_keys=True)
        fh.write('\n')


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv:
        print(__doc__)
        return 1
    if argv[0] == '--dump-api':
        if len(argv) != 2:
            print('error: --dump-api needs an output path', file=sys.stderr)
            return 1
        write_api_json(argv[1])
        print(f'wrote {argv[1]}')
        return 0
    target = 'c'
    rest = []
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == '--target':
            i += 1
            if i >= len(argv):
                print('error: --target needs c or js', file=sys.stderr)
                return 1
            target = argv[i]
        elif a.startswith('--target='):
            target = a.split('=', 1)[1]
        else:
            rest.append(a)
        i += 1
    if target not in ('c', 'js'):
        print(f'error: unknown target {target!r} (c or js)',
              file=sys.stderr)
        return 1
    argv = rest
    src_path = argv[0]
    out_path = argv[argv.index('-o') + 1] if '-o' in argv else None
    try:
        tree = ast.parse(open(src_path).read(), src_path)
        c = Transpiler(tree, target=target).run_transpile()
    except TranspileError as e:
        print(f'{src_path}:{e.lineno}: error: {e.msg}', file=sys.stderr)
        return 1
    if out_path:
        with open(out_path, 'w') as fh:
            fh.write(c)
        print(f'wrote {out_path}')
    else:
        sys.stdout.write(c)
    return 0


def run_transpile(self):
    self.collect()
    for name in self.order:
        self.tag_objects(self.funcs[name])
    # settle locals first so infer_signatures sees them, and settle again
    # after inference (float params/returns can upgrade more locals)
    for name in self.order:
        self.settle_vars(self.funcs[name])
    self.infer_signatures()
    for name in self.order:
        self.settle_vars(self.funcs[name])
    return self.emit()


Transpiler.run_transpile = run_transpile

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
