#!/usr/bin/env python3
# SPDX-FileCopyrightText: Johannes Wilm
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build a standalone "Whale Instructor" desktop app with PyInstaller.

This is a BUILD-TIME tool: PyInstaller is needed only to produce the
bundle, never at runtime (the app stays stdlib-only). The bundle starts
the IDE server and opens the system browser, exactly like `whale-ide`.

Usage:
    python3 tools_build_bundle.py            # single file (slow start)
    python3 tools_build_bundle.py --onedir   # directory bundle (fast start)

Output lands in artifacts/bundle/. Frozen specifics:
  * jobs (build/upload/stop) re-dispatch through the bundle executable via
    WHALE_BUNDLE_MODULE (see serve_ide.module_cmd and the entry below).
  * REPO_ROOT is None, so artifacts resolve under the user data dir; the
    runtime ships inside the package — only the cross toolchain is
    external (`whale-fetch-toolchain fetch`).
"""
import argparse
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PKG = ROOT / 'whale_instructor'
BUILD_DIR = ROOT / 'artifacts' / 'bundle-build'
OUT_DIR = ROOT / 'artifacts' / 'bundle'

# The entry must dispatch child jobs BEFORE touching serve_ide: a frozen
# app has no `python -m`, so serve_ide.module_cmd() re-runs this same
# executable with WHALE_BUNDLE_MODULE set.
ENTRY = '''\
# Generated by tools_build_bundle.py — PyInstaller entry for Whale Instructor.
import os
import runpy

_mod = os.environ.pop('WHALE_BUNDLE_MODULE', None)
if _mod:
    runpy.run_module(_mod, run_name='__main__')
else:
    from whale_instructor.serve_ide import main
    raise SystemExit(main())
'''

SPEC_TEMPLATE = '''\
# Generated by tools_build_bundle.py — do not edit.
a = Analysis(
    [{entry!r}],
    pathex=[{pathex!r}],
    binaries=[],
    datas=[
        ({static!r}, 'whale_instructor/static'),
        ({runtime!r}, 'whale_instructor/runtime'),
        ({progs!r}, 'whale_instructor/progs'),
    ],
    hiddenimports=[],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
)
# api.json ships inside the static/ entry above.
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,{binaries_line}
    name='whale-instructor',
    console={console},
    upx=False,
){collect}
'''


def pyinstaller_cmd(python=None):
    if python:
        return [python, '-m', 'PyInstaller']
    if shutil.which('pyinstaller'):
        return ['pyinstaller']
    r = subprocess.run([sys.executable, '-m', 'PyInstaller', '--version'],
                       capture_output=True, text=True)
    if r.returncode == 0:
        return [sys.executable, '-m', 'PyInstaller']
    print('PyInstaller not found. Install it into a venv, e.g.:\n'
          '    python3 -m venv /tmp/bundle-venv\n'
          '    /tmp/bundle-venv/bin/pip install pyinstaller\n'
          '    /tmp/bundle-venv/bin/python tools_build_bundle.py')
    sys.exit(1)


def check_python(python):
    """Refuse to build with an interpreter that statically links stdlib
    extension modules (no __file__ for _struct): PyInstaller cannot collect
    them, and the frozen app dies at startup with "Module object for
    struct is NULL".
    (Windows CPython always builds _struct into the interpreter and
    PyInstaller handles that fine, so the check is POSIX-only.)"""
    if sys.platform == 'win32':
        return
    r = subprocess.run(
        [python, '-c',
         "import _struct; print(getattr(_struct, '__file__', '') or '')"],
        capture_output=True, text=True)
    if r.returncode != 0:
        print(f'cannot run {python}: {r.stderr.strip()}')
        sys.exit(1)
    if not r.stdout.strip():
        print(f'{python} statically links _struct (no __file__), so '
              'PyInstaller cannot bundle it and the app fails at startup '
              'with "Module object for struct is NULL".\n'
              'Build with a self-consistent interpreter instead, e.g.:\n'
              '    <good-python> -m venv /tmp/bundle-venv\n'
              '    /tmp/bundle-venv/bin/pip install pyinstaller\n'
              '    /tmp/bundle-venv/bin/python tools_build_bundle.py')
        sys.exit(1)


def write_spec(onewfile):
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    entry = BUILD_DIR / 'whale_instructor_bundle.py'
    entry.write_text(ENTRY)
    console = sys.platform == 'win32'       # windowed app on Windows
    if onewfile:
        binaries_line = '\n    a.binaries,\n    a.datas,\n    [],'
        collect = ''
    else:
        binaries_line = '\n    [],\n    exclude_binaries=True,'
        collect = ("\ncoll = COLLECT(exe, a.binaries, a.datas, "
                   "name='whale-instructor')")
    if sys.platform == 'darwin':
        target = 'exe' if onewfile else 'coll'
        collect += (f"\napp = BUNDLE({target}, name='Whale Instructor.app', "
                    "bundle_identifier='org.whaleinstructor.ide')")
    spec = SPEC_TEMPLATE.format(
        entry=str(entry), pathex=str(ROOT), static=str(PKG / 'static'),
        runtime=str(PKG / 'runtime'), progs=str(PKG / 'progs'),
        console=console, binaries_line=binaries_line, collect=collect)
    path = BUILD_DIR / 'whale-instructor.spec'
    path.write_text(spec)
    return path


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--onedir', action='store_true',
                    help='directory bundle (faster startup) instead of onefile')
    ap.add_argument('--python', metavar='PATH',
                    help='interpreter to build with (must have PyInstaller)')
    args = ap.parse_args(argv)
    python = args.python or sys.executable
    check_python(python)
    cmd = pyinstaller_cmd(args.python)
    spec = write_spec(onewfile=not args.onedir)
    print(f'spec: {spec}')
    print(f'output: {OUT_DIR}')
    r = subprocess.run(cmd + ['--noconfirm', '--distpath', str(OUT_DIR),
                              '--workpath', str(BUILD_DIR / 'work'), str(spec)])
    return r.returncode


if __name__ == '__main__':
    sys.exit(main())
